spring.application.name=incidentmanagementapplication

# ===============================
# DATABASE CONFIGURATION
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/IMS
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8001

# ===================================
# SWAGGER
# ===================================
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

# ===============================
# File Upload Configuration
# ===============================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Optional validations
file.upload.allowed-types=application/pdf,image/png,image/jpeg


# ===============================
# Security JWT Configuration
# ===============================
security.jwt.secret=MySuperSecretKeyForJWTThatIsAtLeast32Chars
security.jwt.expiration=86400000

# ===============================
# spring Actuator
# ===============================
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=when_authorized
management.endpoints.web.base-path=/actuator


# ===============================
# Mail properties
# ===============================
spring.mail.host=zmtest.test.local
spring.mail.port=465
spring.mail.username=trng_testuser5@htcindia.in
spring.mail.password=WQC7Eorc7^Jv

# SMTP Properties
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.ssl.trust=*
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
Spring.mail.properties.mail.smtp.writetimeout=5000


# ===============================
# Logging Configuration
# ===============================

# Root logging level
logging.level.root=INFO

# Application packages
logging.level.com.htc.incidentmanagement=DEBUG

# Spring framework (reduce noise)
logging.level.org.springframework=INFO
logging.level.org.springframework.web=INFO
logging.level.org.springframework.security=INFO

# Hibernate SQL (optional – enable only for debugging)
# logging.level.org.hibernate.SQL=DEBUG
# logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Log file output
logging.file.name=logs/incident-management.log

# Log pattern (console)
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n

# Log pattern (file)
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n



